# Generated by Django 4.2.28 on 2026-03-02 17:42

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FormFactor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('length_mm', models.PositiveIntegerField()),
                ('tdp_watts', models.PositiveIntegerField()),
                ('render_score', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PSU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('wattage', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='RamType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('capacity_gb', models.PositiveIntegerField()),
                ('speed_mhz', models.PositiveIntegerField()),
                ('tdp_watts', models.PositiveIntegerField()),
                ('ram_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.ramtype')),
            ],
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('ram_slots', models.PositiveIntegerField()),
                ('max_ram_gb', models.PositiveIntegerField()),
                ('form_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.formfactor')),
                ('ram_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.ramtype')),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.socket')),
            ],
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('tdp_watts', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('has_integrated_gpu', models.BooleanField(default=False)),
                ('single_core_score', models.PositiveIntegerField(default=0)),
                ('socket', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cpus', to='components.socket')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=50)),
                ('max_gpu_length_mm', models.PositiveIntegerField()),
                ('supported_form_factor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='components.formfactor')),
            ],
        ),
    ]
